### ISSUE TITLE
KivaKit build fails due to Hadoop shading

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/kivakit#125]
**Description**
```
┋ Building hadoop-doubly-shaded-protobuf
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:javadoc (default-cli) on project hadoop-doubly-shaded-protobuf: Execution default-cli of goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:javadoc failed: Unable to derive module descriptor for /tmp/maven-repository/org/apache/hadoop/thirdparty/hadoop-shaded-protobuf_3_7/1.1.1/hadoop-shaded-protobuf_3_7-1.1.1.jar: hadoop.shaded.protobuf.3.7: Invalid module name: '3' is not a Java identifier -> [Help 1]
```

**Reproduce Case**
Run the release script

**Comment by jonathanl-telenav** [comment]
This error occurs prior to the above failure:

```
[ERROR]      [copy] Warning: Could not find file /private/tmp/cactus-clone-l5snn2l8-5tvdy1/kivakit-stuff/kivakit-hdfs-filesystem/hdfs-proxy/target/kivakit-hdfs-proxy-1.6.3-SNAPSHOT.jar to copy.
```

**Comment by timboudreau** [comment]
See commit message [here](https://github.com/Telenav/kivakit-stuff/commit/3bab42c6f32f6cf9b6c7c0123952f9afcc643350) for resolution.  @jonathanl-telenav - can you create a standalone git repository for it under the telenav organization?

**Comment by jonathanl-telenav** [comment]
the project works as is with Hadoop out of process. the build is just the beginning of the problems with Hadoop. once you get it running, you'll find that there is a steady stream of applications that can't link to it correctly, each taking hours to fix. suggest we put it back.

**Comment by jonathanl-telenav** [comment]
assign to 1.7.0

**Comment by timboudreau** [comment]
I took both of those out of the build entirely a couple of days ago.  I'm attempting to put together an alternate workaround for getting the hdfs proxy build working.

If you want it working immediately, the easy and simple solution which we've already discussed is simply to move it out of the kivakit tree and build it separately - it cannot be easily modularized, and possibly not at all.

**Comment by timboudreau** [comment]
These are back in the build, but I strongly recommend they move out-of-tree.
