### ISSUE TITLE
kivakit-assets needs versioned documentation

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/kivakit#20]
**Description**
Currently there is only one set of documentation under "docs" in the kivakit-assets project. Instead, there should be docs/[release-version] for each released version. This should be applied to the other *-assets repositories.

docs/0.9.8-alpha/javadoc
docs/0.9.8-alpha/lexakai
docs/0.9.8-alpha/images
docs/0.9.8-alpha/codeflowers

etc.

**Comment by jonathanlocke** [comment]
Scripts and pom files have been updated. When 0.9.8-alpha is released, we may want to remove the javadoc and Lexakai folders in each project that aren't under a versioned directory to make things tidy.
