### ISSUE TITLE
Add interaction diagrams to...

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/kivakit#26]
**What would you like?**
 - kivakit-examples where it makes sense
 - complete hdfs test interaction diagram
 - add interaction diagram for kivakit-configuration
 - add diagram for kivakit-resource that shows how filesystem providers are loaded with FileSystemServiceLoader and used by File.java

**Why would you like it?**
To help people understand program flow

**Comment by jonathanl-telenav** [comment]
Is this ticket complete, Haifeng?

**Comment by haifeng-zhu-tn** [comment]
Yes, I committed puml file with generated class diagram and sequence diagram into:
https://github.com/Telenav/kivakit/tree/master/documentation/uml

e.g. 
https://github.com/Telenav/kivakit/blob/master/documentation/uml/resource/readable-writable-resources-Readable_and_Writable_Resource.svg
https://github.com/Telenav/kivakit/blob/master/documentation/uml/resource/readable-writable-resources-Access_Package_Resource.svg
